/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DatenschutzRouteImport } from './routes/datenschutz'
import { Route as ImpressumRouteImport } from './routes/impressum'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as TeamRouteImport } from './routes/team'
import { Route as UeberUnsRouteImport } from './routes/ueber-uns'
import { Route as KarriereIndexRouteImport } from './routes/karriere.index'
import { Route as KarriereSlugRouteImport } from './routes/karriere.$slug'
import { Route as KarriereBewerbungRouteImport } from './routes/karriere.bewerbung'
import { Route as LeistungenIndexRouteImport } from './routes/leistungen.index'
import { Route as LeistungenSlugRouteImport } from './routes/leistungen.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DatenschutzRoute = DatenschutzRouteImport.update({
  id: '/datenschutz',
  path: '/datenschutz',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpressumRoute = ImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const UeberUnsRoute = UeberUnsRouteImport.update({
  id: '/ueber-uns',
  path: '/ueber-uns',
  getParentRoute: () => rootRouteImport,
} as any)
const KarriereIndexRoute = KarriereIndexRouteImport.update({
  id: '/karriere/',
  path: '/karriere/',
  getParentRoute: () => rootRouteImport,
} as any)
const KarriereSlugRoute = KarriereSlugRouteImport.update({
  id: '/karriere/$slug',
  path: '/karriere/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const KarriereBewerbungRoute = KarriereBewerbungRouteImport.update({
  id: '/karriere/bewerbung',
  path: '/karriere/bewerbung',
  getParentRoute: () => rootRouteImport,
} as any)
const LeistungenIndexRoute = LeistungenIndexRouteImport.update({
  id: '/leistungen/',
  path: '/leistungen/',
  getParentRoute: () => rootRouteImport,
} as any)
const LeistungenSlugRoute = LeistungenSlugRouteImport.update({
  id: '/leistungen/$slug',
  path: '/leistungen/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/kontakt': typeof KontaktRoute
  '/team': typeof TeamRoute
  '/ueber-uns': typeof UeberUnsRoute
  '/karriere/$slug': typeof KarriereSlugRoute
  '/karriere/bewerbung': typeof KarriereBewerbungRoute
  '/leistungen/$slug': typeof LeistungenSlugRoute
  '/karriere/': typeof KarriereIndexRoute
  '/leistungen/': typeof LeistungenIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/kontakt': typeof KontaktRoute
  '/team': typeof TeamRoute
  '/ueber-uns': typeof UeberUnsRoute
  '/karriere/$slug': typeof KarriereSlugRoute
  '/karriere/bewerbung': typeof KarriereBewerbungRoute
  '/leistungen/$slug': typeof LeistungenSlugRoute
  '/karriere': typeof KarriereIndexRoute
  '/leistungen': typeof LeistungenIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/kontakt': typeof KontaktRoute
  '/team': typeof TeamRoute
  '/ueber-uns': typeof UeberUnsRoute
  '/karriere/$slug': typeof KarriereSlugRoute
  '/karriere/bewerbung': typeof KarriereBewerbungRoute
  '/leistungen/$slug': typeof LeistungenSlugRoute
  '/karriere/': typeof KarriereIndexRoute
  '/leistungen/': typeof LeistungenIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/datenschutz'
    | '/impressum'
    | '/kontakt'
    | '/team'
    | '/ueber-uns'
    | '/karriere/$slug'
    | '/karriere/bewerbung'
    | '/leistungen/$slug'
    | '/karriere/'
    | '/leistungen/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/datenschutz'
    | '/impressum'
    | '/kontakt'
    | '/team'
    | '/ueber-uns'
    | '/karriere/$slug'
    | '/karriere/bewerbung'
    | '/leistungen/$slug'
    | '/karriere'
    | '/leistungen'
  id:
    | '__root__'
    | '/'
    | '/datenschutz'
    | '/impressum'
    | '/kontakt'
    | '/team'
    | '/ueber-uns'
    | '/karriere/$slug'
    | '/karriere/bewerbung'
    | '/leistungen/$slug'
    | '/karriere/'
    | '/leistungen/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DatenschutzRoute: typeof DatenschutzRoute
  ImpressumRoute: typeof ImpressumRoute
  KontaktRoute: typeof KontaktRoute
  TeamRoute: typeof TeamRoute
  UeberUnsRoute: typeof UeberUnsRoute
  KarriereSlugRoute: typeof KarriereSlugRoute
  KarriereBewerbungRoute: typeof KarriereBewerbungRoute
  LeistungenSlugRoute: typeof LeistungenSlugRoute
  KarriereIndexRoute: typeof KarriereIndexRoute
  LeistungenIndexRoute: typeof LeistungenIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datenschutz': {
      id: '/datenschutz'
      path: '/datenschutz'
      fullPath: '/datenschutz'
      preLoaderRoute: typeof DatenschutzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impressum': {
      id: '/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof ImpressumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ueber-uns': {
      id: '/ueber-uns'
      path: '/ueber-uns'
      fullPath: '/ueber-uns'
      preLoaderRoute: typeof UeberUnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/karriere/': {
      id: '/karriere/'
      path: '/karriere'
      fullPath: '/karriere/'
      preLoaderRoute: typeof KarriereIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/karriere/$slug': {
      id: '/karriere/$slug'
      path: '/karriere/$slug'
      fullPath: '/karriere/$slug'
      preLoaderRoute: typeof KarriereSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/karriere/bewerbung': {
      id: '/karriere/bewerbung'
      path: '/karriere/bewerbung'
      fullPath: '/karriere/bewerbung'
      preLoaderRoute: typeof KarriereBewerbungRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leistungen/': {
      id: '/leistungen/'
      path: '/leistungen'
      fullPath: '/leistungen/'
      preLoaderRoute: typeof LeistungenIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leistungen/$slug': {
      id: '/leistungen/$slug'
      path: '/leistungen/$slug'
      fullPath: '/leistungen/$slug'
      preLoaderRoute: typeof LeistungenSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DatenschutzRoute: DatenschutzRoute,
  ImpressumRoute: ImpressumRoute,
  KontaktRoute: KontaktRoute,
  TeamRoute: TeamRoute,
  UeberUnsRoute: UeberUnsRoute,
  KarriereSlugRoute: KarriereSlugRoute,
  KarriereBewerbungRoute: KarriereBewerbungRoute,
  LeistungenSlugRoute: LeistungenSlugRoute,
  KarriereIndexRoute: KarriereIndexRoute,
  LeistungenIndexRoute: LeistungenIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
